export const BANK_NAME_LIST: string[] = [
  'Narodowy Bank Polski',
  'PKO BP',
  'Bank Handlowy w Warszawie',
  'Bank Millennium',
  'ING Bank Śląski',
  'Bank BPH',
  'Santander Bank',
  'Bank Gospodarstwa Krajowego',
  'mBank',
  'Bank Handlowo-Kredytowy w Katowicach',
  'Bank Polska Kasa Opieki',
  'HSBC Continental Europe',
  'Bank Pocztowy',
  'DNB Bank',
  'VeloBank',
  'Bank Ochrony Środowiska',
  'BNP Paribas Bank',
  'SGB-Bank',
  'PLUS BANK',
  'Credit Agricole Bank',
  'Danske Bank A/S',
  'Société Générale',
  'BNP Paribas',
  'Nest Bank',
  'Deutsche Bank',
  'Pekao Bank Hipoteczny',
  'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  'Santander Consumer Bank',
  'Volkswagen Bank',
  'CA Auto Bank',
  'mBank Hipoteczny',
  'Toyota Bank',
  'Svenska Handelsbanken',
  'RCI Banque',
  'Raiffeisen Bank International',
  'Skandinaviska Enskilda Banken',
  'CaixaBank',
  'U.S. Bank Europe',
  'HAITONG BANK,',
  'Alior Bank',
  'Aareal Bank Aktiengesellschaft',
  'Citibank Europe plc (Publiczna',
  'Ikano Bank',
  'Nordea Bank',
  'J.P. Morgan',
  'Bank of China',
  'Industrial and Commercial Bank of China',
  'EUROCLEAR Bank',
  'Intesa Sanpaolo',
  'Western Union International Bank',
  'PKO Bank Hipoteczny',
  'TF BANK AB',
  'AS Inbank',
  'China Construction Bank',
  'John Deere Bank',
  'ING Bank Hipoteczny',
  'Goldman Sachs Bank Europe',
  'BFF Bank',
  'Bank Nowy',
  'Allfunds Bank',
  'Hoist Finance',
  'Millennium Bank Hipoteczny',
  'AION Bank',
  'Morgan Stanley Europe',
  'Woori Bank Europe',
  'SkyCash Poland',
  'Quicko spółka z ograniczoną odpowiedzialnością',
  'SPEEDY AG spółka z ograniczoną odpowiedzialnością',
  'SKOK „Szopienice” w Katowicach',
  'SKOK „Centrum”',
  'SKOK im. Eugeniusza Kwiatkowskiego',
  'SKOK Ziemi Rybnickiej',
  'SKOK im. Zygmunta Chmielewskiego',
  'SKOK im. Franciszka Stefczyka',
  'Krakowska Spółdzielcza Kasa Oszczędnościowo-Kredytowa w Krakowie',
  'SKOK przy Dezamet',
  'SKOK "Wisła"',
  'Zachodniopomorska Spółdzielcza Kasa Oszczędnościowo-Kredytowa',
  'SKOK PROGRES',
  'SKOK im. Unii Lubelskiej w Lublinie',
  'Regionalna Spółdzielcza Kasa Oszczędnościowo-Kredytowa im. św. Brata Alberta',
  'Bank Spółdzielczy w Otwocku',
  'Bank Spółdzielczy w Piasecznie',
  'Mazovia Bank Spółdzielczy',
  'Bank Spółdzielczy w Raszynie',
  'Spółdzielczy Bank Rzemiosła i Rolnictwa w Wołominie',
  'Warszawski Bank Spółdzielczy',
  'Bank Spółdzielczy w Tarczynie',
  'Mazowiecki Bank Spółdzielczy w Łomiankach',
  'Bank Spółdzielczy w Nowym Dworze Mazowieckim',
  'Bank Spółdzielczy w Legionowie',
  'Polski Bank Spółdzielczy w Wyszkowie',
  'Bank Spółdzielczy w Nadarzynie',
  'Bank Spółdzielczy w Halinowie',
  'Bank Spółdzielczy w Białej Rawskiej',
  'Bank Spółdzielczy w Karczewie',
  'Bank Spółdzielczy w Białej Podlaskiej',
  'Bank Spółdzielczy w Radzyniu Podlaskim',
  'Bank Spółdzielczy w Parczewie',
  'Bank Spółdzielczy w Trzebieszowie',
  'Bank Spółdzielczy w Łomazach',
  'Bank Spółdzielczy w Międzyrzecu Podlaskim',
  'Bank Spółdzielczy w Łosicach',
  'Wschodni Bank Spółdzielczy w Chełmie',
  'Bank Spółdzielczy w Białymstoku',
  'Bank Spółdzielczy w Bielsku Podlaskim',
  'Bank Spółdzielczy w Brańsku',
  'Bank Spółdzielczy w Sokółce',
  'Bank Spółdzielczy w Siemiatyczach',
  'Bank Spółdzielczy w Hajnówce',
  'Bank Spółdzielczy w Mońkach',
  'Bank Spółdzielczy w Juchnowcu Górnym',
  'Podlaski Bank Spółdzielczy w Knyszynie',
  'Bank Spółdzielczy w Korycinie',
  'Bank Spółdzielczy w Łapach',
  'Bank Spółdzielczy w Narwi',
  'Bank Spółdzielczy w Suchowoli',
  'Podlasko-Mazurski Bank Spółdzielczy w Zabłudowie',
  'ABS Bank Spółdzielczy',
  'Beskidzki Bank Spółdzielczy',
  'Bank Spółdzielczy w Brzeźnicy',
  'Bank Spółdzielczy w Cieszynie',
  'Bank Spółdzielczy w Skoczowie',
  'Bank Spółdzielczy w Ustroniu',
  'Bank Spółdzielczy w Jasienicy',
  'Bank Spółdzielczy w Jeleśni',
  'Bank Spółdzielczy w Kalwarii Zebrzydowskiej',
  'Śląski Bank Spółdzielczy "Silesia" w Katowicach',
  'Bank Spółdzielczy w Jordanowie',
  'Bank Spółdzielczy Ziem Górskich KARPATIA',
  'Bank Spółdzielczy w Porąbce',
  'Bank Spółdzielczy w Rajczy',
  'Bank Spółdzielczy w Suchej Beskidzkiej',
  'Bank Spółdzielczy w Węgierskiej Górce',
  'Bank Spółdzielczy w Bystrej',
  'Bank Spółdzielczy w Zatorze',
  'Bank Spółdzielczy w Żywcu',
  'Bank Spółdzielczy w Gilowicach',
  'Bank Spółdzielczy w Bydgoszczy',
  'Bank Spółdzielczy w Koronowie',
  'Bank Spółdzielczy w Chojnicach',
  'Bank Spółdzielczy w Czersku',
  'InoBank Bank Spółdzielczy w Inowrocławiu',
  'Piastowski Bank Spółdzielczy w Janikowie',
  'Bank Spółdzielczy w Kruszwicy',
  'Bank Spółdzielczy w Pruszczu Pomorskim',
  'Bank Spółdzielczy w Piotrkowie Kujawskim',
  'Bank Spółdzielczy w Gnieźnie',
  'Bank Spółdzielczy w Strzelnie',
  'Bank Spółdzielczy w Więcborku',
  'Bank Spółdzielczy w Szubinie',
  'Bank Spółdzielczy "Pałuki" w Żninie',
  'Bank Spółdzielczy w Kcyni',
  'Bank Spółdzielczy w Barcinie',
  'Bank Spółdzielczy w Świeciu',
  'Bank Spółdzielczy w Osiu',
  'Bank Spółdzielczy w Nowem n/Wisłą',
  'Bank Spółdzielczy w Tucholi',
  'Bank Spółdzielczy w Nakle n/Notecią',
  'Pałucki Bank Spółdzielczy w Wągrowcu',
  'Bank Spółdzielczy w Wojsławicach',
  'Bank Spółdzielczy w Cycowie',
  'Spółdzielczy Bank Powiatowy w Piaskach',
  'Bank Spółdzielczy w Leśniowicach',
  'Bank Spółdzielczy w Krasnymstawie',
  'Bank Spółdzielczy w Białopolu',
  'Bank Spółdzielczy w Raciążu',
  'Bank Spółdzielczy w Grudusku',
  'Bank Spółdzielczy w Działdowie z siedzibą w Lidzbarku',
  'Bank Spółdzielczy w Płońsku',
  'Bank Spółdzielczy w Pułtusku',
  'Bank Spółdzielczy w Żurominie',
  'Bank Spółdzielczy w Mławie',
  'Bank Spółdzielczy w Nasielsku',
  'Bank Spółdzielczy w Glinojecku',
  'Bank Spółdzielczy w Strzegowie',
  'Bank Spółdzielczy w Przasnyszu',
  'Bank Spółdzielczy w Krzepicach',
  'Bank Spółdzielczy w Kłobucku',
  'Częstochowski Bank Spółdzielczy JURA BANK',
  'Bank Spółdzielczy w Mykanowie',
  'Bank Spółdzielczy w Pajęcznie',
  'Bank Spółdzielczy we Włoszczowie',
  'Bank Spółdzielczy w Zawadzkiem',
  'Bank Spółdzielczy w Konopiskach',
  'Bank Spółdzielczy w Szczekocinach',
  'Międzypowiatowy Bank Spółdzielczy w Myszkowie',
  'Bank Spółdzielczy w Gliwicach',
  'Bank Spółdzielczy w Leśnicy',
  'Braniewsko - Pasłęcki Bank Spółdzielczy z siedzibą w Pasłęku',
  'Bank Spółdzielczy w Malborku',
  'Powiślański Bank Spółdzielczy w Kwidzynie',
  'Żuławski Bank Spółdzielczy',
  'Bank Spółdzielczy w Sztumie',
  'Bank Spółdzielczy w Stegnie',
  'Bank Spółdzielczy w Suszu',
  'Bank Spółdzielczy w Prabutach',
  'Bank Spółdzielczy w Sierakowicach',
  'Kaszubski Bank Spółdzielczy',
  'Bank Spółdzielczy w Tczewie',
  'Bank Spółdzielczy w Kościerzynie',
  'Bank Spółdzielczy w Starogardzie Gdańskim',
  'Bank Spółdzielczy w Pruszczu Gdańskim',
  'Bank Spółdzielczy w Pszczółkach',
  'Bank Spółdzielczy w Skórczu',
  'Bank Spółdzielczy w Gniewie',
  'Bank Spółdzielczy w Pucku',
  'Bank Spółdzielczy w Krokowej',
  'Bank Rumia Spółdzielczy',
  'Gospodarczy Bank Spółdzielczy w Barlinku',
  'Lubuski Bank Spółdzielczy',
  'Zachodniopomorski Bank Spółdzielczy',
  'Lubusko-Wielkopolski Bank Spółdzielczy',
  'Gospodarczy Bank Spółdzielczy w Gorzowie Wielkopolskim',
  'Bank Spółdzielczy Pojezierza Międzychodzko - Sierakowskiego w Sierakowie',
  'Bank Spółdzielczy w Ośnie Lubuskim',
  'Bank Spółdzielczy w Rzepinie',
  'Powiatowy Bank Spółdzielczy w Złotoryi',
  'Bank Spółdzielczy w Pieńsku',
  'Łużycki Bank Spółdzielczy w Lubaniu',
  'Bank Spółdzielczy Lwówek Śląski w Lwówku Śląskim',
  'Bank Spółdzielczy w Jaworze',
  'Bank Spółdzielczy w Kamiennej Górze',
  'Bank Spółdzielczy Ziemi Kaliskiej',
  'Bank Spółdzielczy w Pleszewie',
  'Bank Spółdzielczy w Dobrzycy',
  'Bank Spółdzielczy w Krotoszynie',
  'Bank Spółdzielczy w Jarocinie',
  'Spółdzielczy Bank Ludowy w Kępnie',
  'Rejonowy Bank Spółdzielczy w Lututowie',
  'Bank Spółdzielczy w Oleśnicy',
  'Bank Spółdzielczy w Raszkowie',
  'Spółdzielczy Bank Ludowy w Skalmierzycach',
  'Orzesko-Knurowski Bank Spółdzielczy z siedzibą w Knurowie',
  'Bank Spółdzielczy w Tychach',
  'Mikołowski Bank Spółdzielczy w Mikołowie',
  'Bank Spółdzielczy w Będzinie',
  'Bank Spółdzielczy w Wolbromiu',
  'Bank Spółdzielczy w Chrzanowie',
  'Bank Spółdzielczy w Jaworznie',
  'Bank Spółdzielczy w Miedźnej',
  'Bank Spółdzielczy w Pawłowicach',
  'Bank Spółdzielczy w Pszczynie',
  'Bank Spółdzielczy w Olkuszu w likwidacji',
  'Bank Spółdzielczy Czechowice-Dziedzice-Bestwina',
  'Bank Spółdzielczy w Żorach',
  'Bank Spółdzielczy w Tarnowskich Górach',
  'Bank Spółdzielczy w Tworogu',
  'Bank Spółdzielczy w Świerklańcu',
  'Bank Spółdzielczy w Gorzycach',
  'Bank Spółdzielczy w Jastrzębiu-Zdroju',
  'Krakowski Bank Spółdzielczy',
  'Bank Spółdzielczy w Raciborzu',
  'Meander Bank Spółdzielczy w Krzyżanowicach',
  'Bank Spółdzielczy w Kielcach',
  'Bank Spółdzielczy w Busku-Zdroju',
  'Bank Spółdzielczy w Chmielniku',
  'Bank Spółdzielczy Daleszyce-Górno',
  'Świętokrzyski Bank Spółdzielczy w Jędrzejowie',
  'Bank Spółdzielczy w Końskich',
  'Bank Spółdzielczy w Ostrowcu Świętokrzyskim',
  'Bank Spółdzielczy w Łopusznie',
  'Nadwiślański Bank Spółdzielczy w Solcu-Zdroju',
  'Bank Spółdzielczy w Pińczowie',
  'Bank Spółdzielczy w Proszowicach',
  'Bank Spółdzielczy w Samsonowie',
  'Bank Spółdzielczy w Starachowicach',
  'Bank Spółdzielczy w Stopnicy',
  'Bank Spółdzielczy w Suchedniowie',
  'Bank Spółdzielczy w Szydłowie',
  'Bank Spółdzielczy w Wąchocku',
  'Bank Spółdzielczy w Wodzisławiu',
  'Bank Spółdzielczy w Słupcy',
  'Bank Spółdzielczy w Koninie',
  'Bank Spółdzielczy w Ślesinie',
  'Bank Spółdzielczy w Witkowie',
  'Ludowy Bank Spółdzielczy w Strzałkowie',
  'Rejonowy Bank Spółdzielczy w Malanowie',
  'Bank Spółdzielczy w Kłodawie',
  'Bank Spółdzielczy w Wierzbinku',
  'Powiatowy Bank Spółdzielczy we Wrześni',
  'Bank Spółdzielczy w Białogardzie',
  'Pomorski Bank Spółdzielczy w Świdwinie',
  'Bałtycki Bank Spółdzielczy',
  'Bank Spółdzielczy w Połczynie Zdroju',
  'Bank Spółdzielczy w Kaliszu Pomorskim',
  'Bank Spółdzielczy w Sławnie',
  'Bank Spółdzielczy Rzemiosła w Krakowie',
  'Małopolski Bank Spółdzielczy',
  'Bank Spółdzielczy w Słomnikach',
  'Bank Spółdzielczy w Skawinie',
  'Bank Spółdzielczy w Dobczycach',
  'Bank Spółdzielczy w Krzeszowicach',
  'Bieszczadzki Bank Spółdzielczy w Ustrzykach Dolnych',
  'Bank Spółdzielczy w Bieczu',
  'Bank Spółdzielczy w Rymanowie',
  'Bank Spółdzielczy w Kołaczycach',
  'Bank Spółdzielczy w Lipinkach',
  'Bank Spółdzielczy w Dynowie',
  'Bank Spółdzielczy we Wschowie',
  'Bank Spółdzielczy w Chojnowie',
  'Bank Spółdzielczy w Głogowie',
  'Bank Spółdzielczy w Legnicy',
  'Bank Spółdzielczy w Środzie Śląskiej',
  'Bank Spółdzielczy w Poniecu',
  'Bank Spółdzielczy we Włoszakowicach',
  'POZNAŃSKI BANK SPÓŁDZIELCZY',
  'Powiatowy Bank Spółdzielczy w Gostyniu',
  'Bank Spółdzielczy w Kościanie',
  'Bank Spółdzielczy w Śmiglu',
  'Bank Spółdzielczy w Jutrosinie',
  'Rejonowy Bank Spółdzielczy w Bychawie',
  'Bank Spółdzielczy w Niedrzwicy Dużej',
  'Powiatowy Bank Spółdzielczy w Opolu Lubelskim',
  'Bank Spółdzielczy w Poniatowej',
  'Bank Spółdzielczy w Łęcznej',
  'Bank Spółdzielczy w Niemcach',
  'Bank Spółdzielczy Ziemi Kraśnickiej w Kraśniku',
  'Bank Spółdzielczy w Lubartowie',
  'Bank Spółdzielczy w Łukowie',
  'Bank Spółdzielczy w Rykach',
  'Lubelski Bank Spółdzielczy',
  'Bank Spółdzielczy w Kazimierzu Dolnym',
  'Bank Spółdzielczy w Józefowie nad Wisłą',
  'Bank Spółdzielczy w Nałęczowie',
  'Bank Spółdzielczy w Ostrowi Mazowieckiej',
  'Bank Spółdzielczy w Ciechanowcu',
  'Bank Spółdzielczy w Czyżewie',
  'Bank Spółdzielczy w Kolnie',
  'Bank Spółdzielczy w Szczuczynie',
  'Bank Spółdzielczy w Jedwabnem',
  'Bank Spółdzielczy w Zambrowie',
  'Bank Spółdzielczy w Łomży',
  'Spółdzielczy Bank Rozwoju',
  'Hexa Bank Spółdzielczy',
  'Bank Spółdzielczy w Sokołach',
  'Bank Spółdzielczy w Szumowie',
  'Bank Spółdzielczy w Wysokiem Mazowieckiem',
  'AURET BANK Spółdzielczy',
  'Bank Spółdzielczy w Andrespolu',
  'Bank Spółdzielczy w Zgierzu',
  'Łódzki Bank Spółdzielczy',
  'Bank Spółdzielczy w Ozorkowie',
  'Bank Spółdzielczy w Głownie',
  'Bank Spółdzielczy w Grybowie',
  'Bank Spółdzielczy w Czarnym Dunajcu',
  'Pieniński Bank Spółdzielczy',
  'Bank Spółdzielczy w Limanowej',
  'Bank Spółdzielczy w Gorlicach',
  'Bank Spółdzielczy w Nowym Sączu',
  'Bank Spółdzielczy w Jabłonce',
  'Łącki Bank Spółdzielczy',
  'Bank Spółdzielczy w Mszanie Dolnej',
  'Bank Spółdzielczy w Nowym Targu',
  'Bank Spółdzielczy w Piwnicznej - Zdroju',
  'Bank Spółdzielczy w Podegrodziu',
  'Bank Spółdzielczy w Rabie Wyżnej',
  'Bank Spółdzielczy w Starym Sączu',
  'Bank Spółdzielczy w Łososinie Dolnej',
  'Podhalański Bank Spółdzielczy w Zakopanem',
  'Bank Spółdzielczy w Olsztynku',
  'Mazurski Bank Spółdzielczy w Giżycku',
  'Bank Spółdzielczy w Bartoszycach',
  'Warmiński Bank Spółdzielczy',
  'Bank Spółdzielczy w Szczytnie',
  'Bank Spółdzielczy w Reszlu',
  'Bank Spółdzielczy w Iławie',
  'Bank Spółdzielczy w Lubawie',
  'Bank Spółdzielczy w Nidzicy',
  'Morąsko-Zalewski Bank Spółdzielczy',
  'Bank Spółdzielczy w Mrągowie',
  'Warmińsko - Mazurski Bank Spółdzielczy',
  'Bank Spółdzielczy w Brzegu',
  'Bank Spółdzielczy Grodków-Łosiów z siedzibą w Grodkowie',
  'Bank Spółdzielczy w Baborowie',
  'Bank Spółdzielczy w Namysłowie',
  'Bank Spółdzielczy w Głubczycach',
  'Bank Spółdzielczy w Otmuchowie',
  'Bank Spółdzielczy w Wołczynie',
  'Powiatowy Bank Spółdzielczy w Kędzierzynie-Koźlu',
  'Bank Spółdzielczy w Gogolinie',
  'Bank Spółdzielczy w Krapkowicach',
  'Bank Spółdzielczy w Prudniku',
  'Bank Spółdzielczy w Dobrzeniu Wielkim',
  'Bank Spółdzielczy w Łubnianach',
  'Bank Spółdzielczy "Bank Rolników" w Opolu',
  'Bank Spółdzielczy w Białej',
  'Bank Spółdzielczy w Głogówku',
  'Bank Spółdzielczy w Krasnosielcu z siedzibą w Makowie Mazowieckim',
  'Limes Bank Spółdzielczy',
  'Bank Spółdzielczy w Goworowie',
  'Bank Spółdzielczy w Kadzidle',
  'Kurpiowski Bank Spółdzielczy w Myszyńcu',
  'Bank Spółdzielczy w Różanie',
  'Bank Spółdzielczy w Wąsewie',
  'Bank Spółdzielczy w Wieleniu',
  'Bank Spółdzielczy w Jastrowiu',
  'Spółdzielczy Bank Ludowy w Złotowie',
  'Nadnotecki Bank Spółdzielczy',
  'Bank Spółdzielczy w Łobżenicy',
  'Bank Spółdzielczy w Wysokiej',
  'Bank Spółdzielczy w Lipce',
  'Spółdzielczy Bank Ludowy w Zakrzewie',
  'Bank Spółdzielczy w Chodzieży',
  'Bank Spółdzielczy w Czarnkowie',
  'Ludowy Bank Spółdzielczy w Obornikach',
  'Bank Spółdzielczy we Wronkach',
  'Bank Spółdzielczy w Przedborzu',
  'naturoBank Bank Spółdzielczy',
  'ESBANK Bank Spółdzielczy',
  'Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim',
  'Bank Spółdzielczy w Opocznie',
  'Bank Spółdzielczy "MAZOWSZE" w Płocku',
  'Bank Spółdzielczy w Małej Wsi',
  'Bank Spółdzielczy w Staroźrebach',
  'Vistula Bank Spółdzielczy',
  'Bank Spółdzielczy w Iłowie',
  'Bank Spółdzielczy w Gostyninie',
  'Bank Spółdzielczy w Gąbinie',
  'Bank Spółdzielczy w Starej Białej',
  'Bank Spółdzielczy "Wspólna Praca" w Kutnie',
  'Bank Spółdzielczy w Poddębicach',
  'Pobiedzisko - Gośliński Bank Spółdzielczy w Pobiedziskach',
  'Gospodarczy Bank Spółdzielczy w Mosinie',
  'Bank Spółdzielczy w Kostrzynie',
  'BANK SPÓŁDZIELCZY w Środzie Wielkopolskiej',
  'Bank Spółdzielczy w Nowym Tomyślu',
  'Bank Spółdzielczy Duszniki',
  'Bank Spółdzielczy w Grodzisku Wielkopolskim',
  'Spółdzielczy Bank Ludowy im.Ks.P.Wawrzyniaka',
  'Bank Spółdzielczy w Kórniku',
  'Nadobrzański Bank Spółdzielczy w Rakoniewicach',
  'Bank Spółdzielczy w Żurawicy',
  'Bank Spółdzielczy w Lubaczowie',
  'Bank Spółdzielczy w Chłopicach',
  'Bank Spółdzielczy w Łańcucie',
  'Bank Spółdzielczy w Jarosławiu',
  'Bank Spółdzielczy w Przeworsku',
  'Bank Spółdzielczy w Narolu',
  'Bank Spółdzielczy w Radymnie',
  'Bank Spółdzielczy w Rzeszowie',
  'Bank Spółdzielczy Rzemiosła w Radomiu',
  'Bank Spółdzielczy im.Stefczyka w Belsku Dużym',
  'Bank Spółdzielczy w Białobrzegach',
  'Bank Spółdzielczy w Przysusze',
  'Bank Spółdzielczy w Chynowie',
  'Bank Spółdzielczy w Zwoleniu',
  'Bank Spółdzielczy w Grójcu',
  'Bank Spółdzielczy w Iłży',
  'Bank Spółdzielczy w Jasieńcu',
  'Południowo-Mazowiecki Bank Spółdzielczy w Jedlińsku',
  'Bank Spółdzielczy w Lipsku',
  'Bank Spółdzielczy w Radomiu',
  'Bank Spółdzielczy w Pionkach',
  'Bank Spółdzielczy w Skaryszewie',
  'Bank Spółdzielczy w Warce',
  'Bank Spółdzielczy w Błażowej',
  'Bank Spółdzielczy w Głogowie Małopolskim',
  'Bank Spółdzielczy w Lubeni',
  'Bank Spółdzielczy w Niechobrzu',
  'Bank Spółdzielczy w Tyczynie',
  'Bank Spółdzielczy w Strzyżowie',
  'Bank Spółdzielczy w Jasionce',
  'Bank Spółdzielczy w Ropczycach',
  'Bank Spółdzielczy w Sędziszowie Młp.',
  'Bank Spółdzielczy w Wielopolu Skrzyńskim',
  'Bank Spółdzielczy w Żołyni',
  'EXPRESS BANK SPÓŁDZIELCZY',
  'Bank Spółdzielczy w Kolbuszowej',
  'Bank Spółdzielczy w Sokołowie Małopolskim',
  'Bank Spółdzielczy w Mielcu',
  'Bank Spółdzielczy w Przecławiu',
  'Bank Spółdzielczy w Leżajsku',
  'Nadsański Bank Spółdzielczy',
  'Bank Spółdzielczy w Mokobodach',
  'Bank Spółdzielczy w Siedlcach',
  'Międzygminny Bank Spółdzielczy w Zbuczynie',
  'Bank Spółdzielczy w Kałuszynie',
  'Powiatowy Bank Spółdzielczy w Sokołowie Podlaskim',
  'Bank Spółdzielczy w Adamowie',
  'Bank Spółdzielczy w Krzywdzie',
  'Bank Spółdzielczy w Garwolinie',
  'Bank Spółdzielczy w Łaskarzewie',
  'Bank Spółdzielczy w Mińsku Mazowieckim',
  'Powiatowy Bank Spółdzielczy w Węgrowie',
  'Bank Spółdzielczy w Łochowie',
  'Bank Spółdzielczy Ziemi Wieluńskiej',
  'Bank Spółdzielczy w Błaszkach',
  'Bank Spółdzielczy w Sieradzu',
  'Bank Spółdzielczy w Warcie',
  'Nadwarciański Bank Spółdzielczy w Działoszynie',
  'Bank Spółdzielczy w Szadku',
  'Bank Spółdzielczy w Ruścu',
  'Bank Spółdzielczy w Wartkowicach',
  'Ludowy Bank Spółdzielczy w Zduńskiej Woli',
  'Bank Spółdzielczy w Sochaczewie',
  'Bank Spółdzielczy Ziemi Łowickiej w Łowiczu',
  'Bank Spółdzielczy w Skierniewicach',
  'Bank Spółdzielczy w Mszczonowie',
  'Bank Spółdzielczy w Ustce',
  'Bank Spółdzielczy w Bytowie',
  'Bank Spółdzielczy w Człuchowie',
  'Bank Spółdzielczy w Ełku',
  'Bank Spółdzielczy w Bargłowie Kościelnym',
  'Bank Spółdzielczy w Olecku',
  'Bank Spółdzielczy w Węgorzewie',
  'Bank Spółdzielczy w Augustowie',
  'Bank Spółdzielczy w Suwałkach',
  'Bank Spółdzielczy w Sejnach',
  'Bank Spółdzielczy w Rutce-Tartak',
  'Bank Spółdzielczy Ziemi Szczecińskiej',
  'Bank Spółdzielczy w Goleniowie',
  'Bank Spółdzielczy w Chojnie',
  'Bank Spółdzielczy w Gryficach',
  'Bank Spółdzielczy w Wolinie',
  'Bank Spółdzielczy w Tarnobrzegu',
  'Bank Spółdzielczy w Staszowie',
  'Bank Spółdzielczy w Janowie Lubelskim',
  'Bank Spółdzielczy w Ożarowie',
  'Bank Spółdzielczy w Grębowie',
  'Bank Spółdzielczy w Biłgoraju',
  'Bank Spółdzielczy w Połańcu',
  'Bank Spółdzielczy w Zaleszanach',
  'Bank Spółdzielczy w Sandomierzu',
  'Bank Spółdzielczy w Brzesku',
  'Bank Spółdzielczy w Szczucinie',
  'Bank Spółdzielczy w Dąbrowie Tarnowskiej',
  'Bank Spółdzielczy w Pilźnie',
  'Bank Spółdzielczy w Żyrakowie',
  'Bank Spółdzielczy w Radomyślu Wielkim',
  'Bank Spółdzielczy w Brodnicy',
  'Nicolaus Bank Spółdzielczy w Toruniu',
  'Bank Spółdzielczy w Grębocinie',
  'Bank Spółdzielczy w Golubiu - Dobrzyniu',
  'Bank Spółdzielczy w Kowalewie Pomorskim',
  'Bank Spółdzielczy w Łasinie',
  'Bank Spółdzielczy w Ząbkowicach Śląskich',
  'Bank Spółdzielczy w Kłodzku',
  'Bank Spółdzielczy w Świdnicy',
  'Gospodarczy Bank Spółdzielczy Radków z/s w Nowej Rudzie',
  'Bank Spółdzielczy w Dzierżoniowie',
  'Gospodarczy Bank Spółdzielczy w Strzelinie',
  'Kujawski Bank Spółdzielczy w Aleksandrowie Kujawskim',
  'Bank Spółdzielczy w Kowalu',
  'Bank Spółdzielczy w Lipnie',
  'Kujawsko-Dobrzyński Bank Spółdzielczy',
  'Bank Spółdzielczy w Skępem',
  'Bank Spółdzielczy w Radziejowie',
  'Bank Spółdzielczy w Lubrańcu',
  'Bank Spółdzielczy w Obornikach Śląskich',
  'Bank Spółdzielczy w Miliczu',
  'Bank Spółdzielczy w Oławie',
  'Bank Spółdzielczy w Kątach Wrocławskich',
  'Bank Spółdzielczy w Kobierzycach',
  'Bank Spółdzielczy w Trzebnicy',
  'Bank Spółdzielczy w Żmigrodzie',
  'Bank Spółdzielczy w Tomaszowie Lubelskim',
  'Powiatowy Bank Spółdzielczy w Zamościu',
  'Bank Spółdzielczy we Frampolu',
  'Bank Spółdzielczy w Werbkowicach',
  'Bank Spółdzielczy w Izbicy',
  'Bank Spółdzielczy w Lubyczy Królewskiej',
  'Bank Spółdzielczy w Łukowej',
  'Bank Spółdzielczy w Obszy',
  'Bank Spółdzielczy w Tarnogrodzie',
  'Bank Spółdzielczy w Szczebrzeszynie',
  'Bank Spółdzielczy w Biszczy',
  'Bank Spółdzielczy w Kożuchowie',
  'Bank Spółdzielczy w Siedlcu',
  'Bank Spółdzielczy w Krośnie Odrzańskim',
  'Bank Spółdzielczy w Żaganiu',
  'Bank Spółdzielczy w Iłowej',
  'Bank Spółdzielczy w Nowej Soli',
];
