import { removeWhitespace } from './_utils';

const IBAN_COUNTRY_DATA: Record<string, { country: string; length: number }> = {
  AL: { country: 'Albania', length: 28 },
  AD: { country: 'Andora', length: 24 },
  AT: { country: 'Austria', length: 20 },
  AZ: { country: 'Azerbejdżan', length: 28 },
  BH: { country: 'Bahrajn', length: 22 },
  BY: { country: 'Białoruś', length: 28 },
  BE: { country: 'Belgia', length: 16 },
  BA: { country: 'Bośnia i Hercegowina', length: 20 },
  BR: { country: 'Brazylia', length: 29 },
  BG: { country: 'Bułgaria', length: 22 },
  BI: { country: 'Burundi', length: 27 },
  CR: { country: 'Kostaryka', length: 22 },
  HR: { country: 'Chorwacja', length: 21 },
  CY: { country: 'Cypr', length: 28 },
  CZ: { country: 'Czechy', length: 24 },
  DK: { country: 'Dania', length: 18 },
  DJ: { country: 'Dżibuti', length: 27 },
  DO: { country: 'Dominikana', length: 28 },
  EG: { country: 'Egipt', length: 29 },
  SV: { country: 'Salwador', length: 28 },
  EE: { country: 'Estonia', length: 20 },
  FK: { country: 'Falklandy', length: 18 },
  FO: { country: 'Wyspy Owcze', length: 18 },
  FI: { country: 'Finlandia', length: 18 },
  FR: { country: 'Francja', length: 27 },
  GE: { country: 'Gruzja', length: 22 },
  DE: { country: 'Niemcy', length: 22 },
  GI: { country: 'Gibraltar', length: 23 },
  GR: { country: 'Grecja', length: 27 },
  GL: { country: 'Grenlandia', length: 18 },
  GT: { country: 'Gwatemala', length: 28 },
  VA: { country: 'Watykan', length: 22 },
  HU: { country: 'Węgry', length: 28 },
  IS: { country: 'Islandia', length: 26 },
  IQ: { country: 'Irak', length: 23 },
  IE: { country: 'Irlandia', length: 22 },
  IL: { country: 'Izrael', length: 23 },
  IT: { country: 'Włochy', length: 27 },
  JO: { country: 'Jordania', length: 30 },
  KZ: { country: 'Kazachstan', length: 20 },
  XK: { country: 'Kosowo', length: 20 },
  KW: { country: 'Kuwejt', length: 30 },
  LV: { country: 'Łotwa', length: 21 },
  LB: { country: 'Liban', length: 28 },
  LY: { country: 'Libia', length: 25 },
  LI: { country: 'Liechtenstein', length: 21 },
  LT: { country: 'Litwa', length: 20 },
  LU: { country: 'Luksemburg', length: 20 },
  MT: { country: 'Malta', length: 31 },
  MR: { country: 'Mauretania', length: 27 },
  MU: { country: 'Mauritius', length: 30 },
  MD: { country: 'Mołdawia', length: 24 },
  MC: { country: 'Monako', length: 27 },
  MN: { country: 'Mongolia', length: 20 },
  ME: { country: 'Czarnogóra', length: 22 },
  NL: { country: 'Holandia', length: 18 },
  NI: { country: 'Nikaragua', length: 28 },
  MK: { country: 'Macedonia Północna', length: 19 },
  NO: { country: 'Norwegia', length: 15 },
  PK: { country: 'Pakistan', length: 24 },
  PS: { country: 'Palestyna', length: 29 },
  PL: { country: 'Polska', length: 28 },
  PT: { country: 'Portugalia', length: 25 },
  QA: { country: 'Katar', length: 29 },
  RO: { country: 'Rumunia', length: 24 },
  RU: { country: 'Rosja', length: 33 },
  LC: { country: 'Saint Lucia', length: 32 },
  SM: { country: 'San Marino', length: 27 },
  ST: { country: 'Wyspy Świętego Tomasza i Książęca', length: 25 },
  SA: { country: 'Arabia Saudyjska', length: 24 },
  RS: { country: 'Serbia', length: 22 },
  SC: { country: 'Seszele', length: 31 },
  SK: { country: 'Słowacja', length: 24 },
  SI: { country: 'Słowenia', length: 19 },
  SO: { country: 'Somalia', length: 23 },
  ES: { country: 'Hiszpania', length: 24 },
  SD: { country: 'Sudan', length: 18 },
  OM: { country: 'Oman', length: 23 },
  SE: { country: 'Szwecja', length: 24 },
  CH: { country: 'Szwajcaria', length: 21 },
  TL: { country: 'Timor Wschodni', length: 23 },
  TN: { country: 'Tunezja', length: 24 },
  TR: { country: 'Turcja', length: 26 },
  UA: { country: 'Ukraina', length: 29 },
  AE: { country: 'Zjednoczone Emiraty Arabskie', length: 23 },
  GB: { country: 'Wielka Brytania', length: 22 },
  VG: { country: 'Brytyjskie Wyspy Dziewicze', length: 24 },
  YE: { country: 'Jemen', length: 30 },
};

const BANK_NAMES: Record<string, string> = {
  '101': 'Narodowy Bank Polski',
  '102': 'PKO Bank Polski',
  '103': 'Bank Handlowy (Citi Handlowy)',
  '104': 'Bank Millennium',
  '105': 'ING Bank Śląski',
  '106': 'Bank BPH',
  '109': 'Santander Bank Polska',
  '113': 'Bank Gospodarstwa Krajowego',
  '114': 'mBank',
  '116': 'Bank Millennium',
  '122': 'Bank Handlowo-Kredytowy w Katowicach',
  '124': 'Pekao SA',
  '128': 'HSBC Continental Europe',
  '132': 'Bank Pocztowy',
  '137': 'DNB Bank Polska',
  '139': 'Santander Bank Polska',
  '144': 'PKO BP',
  '146': 'VeloBank',
  '147': 'Bank Millennium',
  '150': 'Santander Bank Polska',
  '151': 'mBank',
  '152': 'VeloBank',
  '154': 'Bank Ochrony Środowiska',
  '156': 'VeloBank',
  '157': 'HSBC Continental Europe',
  '160': 'BNP Paribas Bank Polska',
  '161': 'SGB-Bank',
  '163': 'mBank',
  '168': 'PLUS BANK',
  '171': 'Bank BPH',
  '175': 'BNP Paribas Bank Polska',
  '179': 'Credit Agricole Bank Polska',
  '180': 'ING Bank Śląski',
  '182': 'Bank Handlowy (Citi Handlowy)',
  '183': 'Danske Bank A/S',
  '184': 'Société Générale',
  '186': 'BNP Paribas S.A.',
  '187': 'Nest Bank',
  '188': 'Deutsche Bank Polska',
  '189': 'Pekao Bank Hipoteczny',
  '190': 'Bank BPH',
  '191': 'Santander Bank Polska',
  '193': 'Bank Polskiej Spółdzielczości',
  '194': 'Credit Agricole Bank Polska',
  '195': 'Pekao SA',
  '196': 'Santander Consumer Bank',
  '197': 'ING Bank Śląski',
  '200': 'BNP Paribas Bank Polska',
  '201': 'Bank Polskiej Spółdzielczości',
  '202': 'Bank Polskiej Spółdzielczości',
  '204': 'SGB-Bank',
  '205': 'Bank Polskiej Spółdzielczości',
  '206': 'SGB-Bank',
  '208': 'SGB-Bank',
  '210': 'Bank Polskiej Spółdzielczości',
  '211': 'Bank Polskiej Spółdzielczości',
  '212': 'Santander Consumer Bank',
  '213': 'Volkswagen Bank',
  '214': 'CA Auto Bank',
  '215': 'mBank Hipoteczny',
  '216': 'Toyota Bank Polska',
  '218': 'ING Bank Śląski',
  '219': 'DNB Bank Polska',
  '220': 'Svenska Handelsbanken',
  '225': 'Svenska Handelsbanken',
  '226': 'RCI Banque',
  '229': 'VeloBank',
  '233': 'Credit Agricole Bank Polska',
  '234': 'Raiffeisen Bank International',
  '235': 'BNP Paribas',
  '236': 'Danske Bank',
  '237': 'Skandinaviska Enskilda Banken',
  '239': 'CaixaBank Polska',
  '241': 'U.S. Bank Europe Designated Activity Company',
  '243': 'BNP Paribas',
  '247': 'Haitong Bank',
  '248': 'VeloBank',
  '249': 'Alior Bank',
  '251': 'Aareal Bank Aktiengesellschaft',
  '253': 'Nest Bank',
  '254': 'Citibank Europe',
  '255': 'Ikano Bank',
  '256': 'Nordea Bank',
  '258': 'J.P. Morgan SE',
  '260': 'Bank of China',
  '262': 'Industrial and Commercial Bank of China',
  '264': 'RCI Banque',
  '265': 'EUROCLEAR Bank SA/NV',
  '266': 'Intesa Sanpaolo',
  '267': 'Western Union.',
  '269': 'PKO Bank Hipoteczny',
  '270': 'TF BANK AB',
  '272': 'AS Inbank',
  '273': 'China Construction Bank',
  '275': 'John Deere Bank',
  '277': 'Volkswagen Bank',
  '278': 'ING Bank Hipoteczny',
  '279': 'Raiffeisen Bank International',
  '280': 'HSBC Continental Europe',
  '281': 'Goldman Sachs Bank Europe',
  '283': 'J.P. Morgan',
  '285': 'BFF Bank',
  '286': 'CA Auto Bank',
  '287': 'Bank Nowy',
  '288': 'Allfunds Bank',
  '289': 'Hoist Finance',
  '290': 'Millennium Bank Hipoteczny',
  '291': 'AION Bank',
  '293': 'VeloBank',
  '294': 'Morgan Stanley Europe',
  '296': 'Woori Bank Europe',
  '800': 'Bank Spółdzielczy w Otwocku',
  '801': 'Bank Spółdzielczy w Halinowie',
  '802': 'Bank Spółdzielczy w Karczewie',
  '803': 'Bank Spółdzielczy w Trzebieszowie',
  '804': 'Bank Spółdzielczy w Łomazach',
  '805': 'Bank Spółdzielczy w Białej Podlaskiej',
  '806': 'Bank Spółdzielczy w Białymstoku',
  '808': 'Bank Spółdzielczy w Hajnówce',
  '809': 'Bank Spółdzielczy w Sokółce',
  '811': 'Bank Spółdzielczy w Kalwarii Zebrzydowskiej',
  '812': 'Bank Spółdzielczy w Porąbce',
  '813': 'ABS Bank Spółdzielczy',
  '815': 'Bank Spółdzielczy w Piotrkowie Kujawskim',
  '817': 'Bank Spółdzielczy w Nakle n/Notecią',
  '818': 'Wschodni Bank Spółdzielczy w Chełmie',
  '819': 'Bank Spółdzielczy w Leśniowicach',
  '820': 'Bank Spółdzielczy w Leśniowicach',
  '821': 'Bank Spółdzielczy w Pułtusku',
  '822': 'Bank Spółdzielczy w Glinojecku',
  '823': 'Bank Spółdzielczy w Płońsku',
  '824': 'Bank Spółdzielczy w Pułtusku',
  '825': 'Bank Spółdzielczy w Krzepicach',
  '826': 'Częstochowski Bank Spółdzielczy JURA BANK',
  '827': 'Bank Spółdzielczy w Konopiskach',
  '828': 'Międzypowiatowy Bank Spółdzielczy w Myszkowie',
  '829': 'Międzypowiatowy Bank Spółdzielczy w Myszkowie',
  '830': 'Bank Spółdzielczy w Malborku',
  '831': 'Braniewsko-Pasłęcki Bank Spółdzielczy',
  '832': 'Bank Spółdzielczy w Sierakowicach',
  '833': 'Bank Spółdzielczy w Starogardzie Gdańskim',
  '834': 'Bank Spółdzielczy w Skórczu',
  '835': 'Gospodarczy Bank Spółdzielczy w Barlinku',
  '837': 'Bank Spółdzielczy w Rzepinie',
  '838': 'Bank Spółdzielczy Lwówek Śląski w Lwówku Śląskim',
  '840': 'Bank Spółdzielczy w Pleszewie',
  '841': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '843': 'Bank Spółdzielczy w Będzinie',
  '844': 'Bank Spółdzielczy w Pszczynie',
  '845': 'Bank Spółdzielczy Czechowice-Dziedzice-Bestwina',
  '846': 'Mikołowski Bank Spółdzielczy w Mikołowie',
  '849': 'Bank Spółdzielczy w Łopusznie',
  '851': 'Bank Spółdzielczy w Kielcach',
  '853': 'Bank Spółdzielczy w Witkowie',
  '854': 'Bank Spółdzielczy w Kłodawie',
  '855': 'Bank Spółdzielczy w Witkowie',
  '856': 'Ludowy Bank Spółdzielczy w Strzałkowie',
  '857': 'Bank Spółdzielczy w Sławnie',
  '858': 'Bank Spółdzielczy w Kaliszu Pomorskim',
  '859': 'Krakowski Bank Spółdzielczy',
  '862': 'Bank Spółdzielczy w Lipinkach',
  '865': 'Bank Spółdzielczy we Wschowie',
  '866': 'Bank Spółdzielczy we Wschowie',
  '868': 'Rejonowy Bank Spółdzielczy w Bychawie',
  '869': 'Rejonowy Bank Spółdzielczy w Bychawie',
  '870': 'Bank Spółdzielczy w Niemcach',
  '871': 'Bank Spółdzielczy w Lubartowie',
  '872': 'Bank Spółdzielczy w Radzyniu Podlaskim',
  '873': 'Powiatowy Bank Spółdzielczy w Opolu Lubelskim',
  '874': 'Powiatowy Bank Spółdzielczy w Opolu Lubelskim',
  '875': 'Bank Spółdzielczy w Kolnie',
  '877': 'Bank Spółdzielczy w Mońkach',
  '878': 'Bank Spółdzielczy Ziemi Kaliskiej',
  '879': 'Bank Spółdzielczy w Limanowej',
  '880': 'Łącki Bank Spółdzielczy',
  '882': 'Bank Spółdzielczy w Bartoszycach',
  '883': 'Bank Spółdzielczy w Nidzicy',
  '884': 'Bank Spółdzielczy w Szczytnie',
  '885': 'Bank Spółdzielczy w Bartoszycach',
  '886': 'Bank Spółdzielczy w Namysłowie',
  '887': 'Bank Spółdzielczy w Zawadzkiem',
  '888': 'Bank Spółdzielczy w Gogolinie',
  '890': 'Bank Spółdzielczy w Zawadzkiem',
  '891': 'Kurpiowski Bank Spółdzielczy w Myszyńcu',
  '892': 'Bank Spółdzielczy w Krasnosielcu',
  '893': 'Bank Spółdzielczy w Pułtusku',
  '894': 'Spółdzielczy Bank Ludowy w Złotowie',
  '895': 'Lubusko-Wielkopolski Bank Spółdzielczy',
  '896': 'naturoBank Bank Spółdzielczy',
  '898': 'Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim',
  '899': 'Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim',
  '900': 'Bank Spółdzielczy "MAZOWSZE" w Płocku',
  '901': 'Bank Spółdzielczy "MAZOWSZE" w Płocku',
  '903': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '904': 'Bank Spółdzielczy "Wspólna Praca" w Kutnie',
  '905': 'Powiatowy Bank Spółdzielczy we Wrześni',
  '906': 'Bank Spółdzielczy w Gnieźnie',
  '907': 'Bank Spółdzielczy Pojezierza Międzychodzko-Sierakowskiego w Sierakowie',
  '908': 'Bank Spółdzielczy Duszniki',
  '911': 'Bank Spółdzielczy Rzemiosła w Radomiu',
  '912': 'Bank Spółdzielczy w Zwoleniu',
  '913': 'Bank Spółdzielczy w Przysusze',
  '914': 'Bank Spółdzielczy Rzemiosła w Radomiu',
  '915': 'Bank Spółdzielczy Rzemiosła w Radomiu',
  '916': 'Bank Spółdzielczy w Strzyżowie',
  '917': 'Bank Spółdzielczy w Sędziszowie Młp.',
  '918': 'Bank Spółdzielczy w Przecławiu',
  '919': 'Bank Spółdzielczy w Siedlcach',
  '920': 'Bank Spółdzielczy w Krzywdzie',
  '921': 'Bank Spółdzielczy w Rykach',
  '922': 'Bank Spółdzielczy w Mińsku Mazowieckim',
  '923': 'Powiatowy Bank Spółdzielczy w Sokołowie Podlaskim',
  '924': 'Bank Spółdzielczy w Warcie',
  '925': 'Nadwarciański Bank Spółdzielczy w Działoszynie',
  '926': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '928': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '929': 'Bank Spółdzielczy w Skierniewicach',
  '931': 'Bank Spółdzielczy w Ustce',
  '932': 'Bank Spółdzielczy w Bytowie',
  '933': 'Bank Spółdzielczy w Ustce',
  '934': 'Mazurski Bank Spółdzielczy w Giżycku',
  '935': 'Bank Spółdzielczy w Sejnach',
  '936': 'Bank Spółdzielczy w Sejnach',
  '937': 'Bank Spółdzielczy Ziemi Szczecińskiej',
  '938': 'Bank Spółdzielczy w Chojnie',
  '939': 'Bank Spółdzielczy w Tarnobrzegu',
  '940': 'Nadsański Bank Spółdzielczy',
  '941': 'Nadwiślański Bank Spółdzielczy w Solcu-Zdroju',
  '942': 'Bank Spółdzielczy w Sandomierzu',
  '943': 'Bank Spółdzielczy w Tarnobrzegu',
  '944': 'Bank Spółdzielczy Rzemiosła w Krakowie',
  '946': 'Bank Spółdzielczy Rzemiosła w Krakowie',
  '947': 'Bank Spółdzielczy w Pilźnie',
  '948': 'Bank Spółdzielczy w Brodnicy',
  '949': 'Bank Spółdzielczy w Brodnicy',
  '950': 'Bank Spółdzielczy w Łasinie',
  '951': 'Bank Spółdzielczy w Ząbkowicach Śląskich',
  '952': 'Bank Spółdzielczy w Ząbkowicach Śląskich',
  '953': 'Bank Spółdzielczy w Jaworze',
  '954': 'Kujawsko-Dobrzyński Bank Spółdzielczy',
  '957': 'Bank Spółdzielczy w Oławie',
  '959': 'Bank Spółdzielczy w Żmigrodzie',
  '960': 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  '961': 'Bank Spółdzielczy w Izbicy',
  '962': 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  '963': 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  '964': 'Powiatowy Bank Spółdzielczy w Zamościu',
  '965': 'Bank Spółdzielczy w Środzie Śląskiej',
  '966': 'Bank Spółdzielczy w Siedlcu',
  '967': 'Bank Spółdzielczy w Żaganiu',
};

const BANK_FULL_NAMES: Record<string, string> = {
  '101': 'Narodowy Bank Polski',
  '102': 'Powszechna Kasa Oszczędności Bank Polski Spółka Akcyjna',
  '103': 'Bank Handlowy w Warszawie Spółka Akcyjna',
  '104': 'Bank Millennium Spółka Akcyjna',
  '105': 'ING Bank Śląski Spółka Akcyjna',
  '106': 'Bank BPH Spółka Akcyjna',
  '109': 'Santander Bank Polska Spółka Akcyjna',
  '113': 'Bank Gospodarstwa Krajowego',
  '114': 'mBank Spółka Akcyjna',
  '116': 'Bank Millennium Spółka Akcyjna',
  '122': 'Bank Handlowo-Kredytowy Spółka Akcyjna w Katowicach w likwidacji',
  '124': 'Bank Polska Kasa Opieki Spółka Akcyjna',
  '128': 'HSBC Continental Europe (Spółka Akcyjna) Oddział w Polsce',
  '132': 'Bank Pocztowy Spółka Akcyjna',
  '137': 'DNB Bank Polska Spółka Akcyjna',
  '139': 'Santander Bank Polska Spółka Akcyjna',
  '144': 'Powszechna Kasa Oszczędności Bank Polski Spółka Akcyjna',
  '146': 'VeloBank Spółka Akcyjna',
  '147': 'Bank Millennium Spółka Akcyjna',
  '150': 'Santander Bank Polska Spółka Akcyjna',
  '151': 'mBank Spółka Akcyjna',
  '152': 'VeloBank Spółka Akcyjna',
  '154': 'Bank Ochrony Środowiska Spółka Akcyjna',
  '156': 'VeloBank Spółka Akcyjna',
  '157': 'HSBC Continental Europe (Spółka Akcyjna) Oddział w Polsce',
  '160': 'BNP Paribas Bank Polska Spółka Akcyjna',
  '161': 'SGB-Bank Spółka Akcyjna',
  '163': 'mBank Spółka Akcyjna',
  '168': 'PLUS BANK Spółka Akcyjna',
  '171': 'Bank BPH Spółka Akcyjna',
  '175': 'BNP Paribas Bank Polska Spółka Akcyjna',
  '179': 'Credit Agricole Bank Polska Spółka Akcyjna',
  '180': 'ING Bank Śląski Spółka Akcyjna',
  '182': 'Bank Handlowy w Warszawie Spółka Akcyjna',
  '183': 'Danske Bank A/S Spółka Akcyjna Oddział w Polsce',
  '184': 'Société Générale Spółka Akcyjna Oddział w Polsce',
  '186': 'BNP Paribas S.A. Oddział w Polsce',
  '187': 'Nest Bank Spółka Akcyjna',
  '188': 'Deutsche Bank Polska Spółka Akcyjna',
  '189': 'Pekao Bank Hipoteczny Spółka Akcyjna',
  '190': 'Bank BPH Spółka Akcyjna',
  '191': 'Santander Bank Polska Spółka Akcyjna',
  '193': 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  '194': 'Credit Agricole Bank Polska Spółka Akcyjna',
  '195': 'Bank Polska Kasa Opieki Spółka Akcyjna',
  '196': 'Santander Consumer Bank Spółka Akcyjna',
  '197': 'ING Bank Śląski Spółka Akcyjna',
  '200': 'BNP Paribas Bank Polska Spółka Akcyjna',
  '201': 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  '202': 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  '204': 'SGB-Bank Spółka Akcyjna',
  '205': 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  '206': 'SGB-Bank Spółka Akcyjna',
  '208': 'SGB-Bank Spółka Akcyjna',
  '210': 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  '211': 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  '212': 'Santander Consumer Bank Spółka Akcyjna',
  '213': 'Volkswagen Bank GmbH Spółka z ograniczoną odpowiedzialnością Oddział w Polsce',
  '214': 'CA Auto Bank S.p.A. Spółka Akcyjna Oddział w Polsce',
  '215': 'mBank Hipoteczny Spółka Akcyjna',
  '216': 'Toyota Bank Polska Spółka Akcyjna',
  '218': 'ING Bank Śląski Spółka Akcyjna',
  '219': 'DNB Bank Polska Spółka Akcyjna',
  '220': 'Svenska Handelsbanken AB Spółka Akcyjna Oddział w Polsce',
  '225': 'Svenska Handelsbanken AB Spółka Akcyjna Oddział w Polsce',
  '226': 'RCI Banque Spółka Akcyjna Oddział w Polsce',
  '229': 'VeloBank Spółka Akcyjna',
  '233': 'Credit Agricole Bank Polska Spółka Akcyjna',
  '234': 'Raiffeisen Bank International AG (Spółka Akcyjna) Oddział w Polsce',
  '235': 'BNP Paribas S.A. Oddział w Polsce',
  '236': 'Danske Bank A/S Spółka Akcyjna Oddział w Polsce',
  '237': 'Skandinaviska Enskilda Banken AB (Spółka Akcyjna) - Oddział w Polsce',
  '239': 'CAIXABANK, S.A. (SPÓŁKA AKCYJNA) ODDZIAŁ W POLSCE',
  '241':
    'U.S. Bank Europe Designated Activity Company (Spółka z o.o. o Wyznaczonym Przedmiocie Działalności) Oddział w Polsce',
  '243': 'BNP Paribas S.A. Oddział w Polsce',
  '247': 'HAITONG BANK, S.A. Spółka Akcyjna Oddział w Polsce',
  '248': 'VeloBank Spółka Akcyjna',
  '249': 'Alior Bank Spółka Akcyjna',
  '251': 'Aareal Bank Aktiengesellschaft (Spółka Akcyjna) - Oddział w Polsce',
  '253': 'Nest Bank Spółka Akcyjna',
  '254': 'Citibank Europe plc (Publiczna Spółka Akcyjna) Oddział w Polsce',
  '255': 'Ikano Bank AB (publ) Spółka Akcyjna Oddział w Polsce',
  '256': 'Nordea Bank Abp Spółka Akcyjna Oddział w Polsce',
  '258': 'J.P. Morgan SE (Spółka Europejska) Oddział w Polsce',
  '260': 'Bank of China (Europe) S.A. Spółka Akcyjna Oddział w Polsce',
  '262': 'Industrial and Commercial Bank of China (Europe) S.A. (Spółka Akcyjna) Oddział w Polsce',
  '264': 'RCI Banque Spółka Akcyjna Oddział w Polsce',
  '265': 'EUROCLEAR Bank SA/NV (Spółka Akcyjna) - Oddział w Polsce',
  '266': 'Intesa Sanpaolo S.p.A. Spółka Akcyjna Oddział w Polsce',
  '267': 'Western Union International Bank GmbH, Sp. z o.o. Oddział w Polsce',
  '269': 'PKO Bank Hipoteczny Spółka Akcyjna',
  '270': 'TF BANK AB (Spółka Akcyjna) Oddział w Polsce',
  '272': 'AS Inbank Spółka Akcyjna - Oddział w Polsce',
  '273': 'China Construction Bank (Europe) S.A. (Spółka Akcyjna) Oddział w Polsce',
  '275': 'John Deere Bank S.A. Spółka Akcyjna Oddział w Polsce',
  '277': 'Volkswagen Bank GmbH Spółka z ograniczoną odpowiedzialnością Oddział w Polsce',
  '278': 'ING Bank Hipoteczny Spółka Akcyjna',
  '279': 'Raiffeisen Bank International AG (Spółka Akcyjna) Oddział w Polsce',
  '280': 'HSBC Continental Europe (Spółka Akcyjna) Oddział w Polsce',
  '281': 'Goldman Sachs Bank Europe SE Spółka Europejska Oddział w Polsce',
  '283': 'J.P. Morgan SE (Spółka Europejska) Oddział w Polsce',
  '285': 'BFF Bank S.p.A. Spółka Akcyjna Oddział w Polsce',
  '286': 'CA Auto Bank S.p.A. Spółka Akcyjna Oddział w Polsce',
  '287': 'Bank Nowy Spółka Akcyjna',
  '288': 'Allfunds Bank S.A.U. (Spółka Akcyjna) Oddział w Polsce',
  '289': 'Hoist Finance AB (publ) Spółka Akcyjna Oddział w Polsce',
  '290': 'Millennium Bank Hipoteczny Spółka Akcyjna',
  '291': 'AION Bank S.A. Spółka Akcyjna Oddział w Polsce',
  '293': 'VeloBank Spółka Akcyjna',
  '294': 'Morgan Stanley Europe SE (Spółka Europejska) Oddział w Polsce',
  '296': 'Woori Bank Europe GmbH spółka z ograniczoną odpowiedzialnością Oddział w Polsce',
  '800': 'Bank Spółdzielczy w Otwocku',
  '801': 'Bank Spółdzielczy w Halinowie',
  '802': 'Bank Spółdzielczy w Karczewie',
  '803': 'Bank Spółdzielczy w Trzebieszowie',
  '804': 'Bank Spółdzielczy w Łomazach',
  '805': 'Bank Spółdzielczy w Białej Podlaskiej',
  '806': 'Bank Spółdzielczy w Białymstoku',
  '808': 'Bank Spółdzielczy w Hajnówce',
  '809': 'Bank Spółdzielczy w Sokółce',
  '811': 'Bank Spółdzielczy w Kalwarii Zebrzydowskiej',
  '813': 'ABS Bank Spółdzielczy',
  '815': 'Bank Spółdzielczy w Piotrkowie Kujawskim',
  '817': 'Bank Spółdzielczy w Nakle n/Notecią',
  '818': 'Wschodni Bank Spółdzielczy w Chełmie',
  '819': 'Bank Spółdzielczy w Leśniowicach',
  '820': 'Bank Spółdzielczy w Leśniowicach',
  '821': 'Bank Spółdzielczy w Pułtusku',
  '822': 'Bank Spółdzielczy w Glinojecku',
  '823': 'Bank Spółdzielczy w Płońsku',
  '824': 'Bank Spółdzielczy w Pułtusku',
  '825': 'Bank Spółdzielczy w Krzepicach',
  '826': 'Częstochowski Bank Spółdzielczy JURA BANK',
  '827': 'Bank Spółdzielczy w Konopiskach',
  '828': 'Międzypowiatowy Bank Spółdzielczy w Myszkowie',
  '829': 'Międzypowiatowy Bank Spółdzielczy w Myszkowie',
  '830': 'Bank Spółdzielczy w Malborku',
  '831': 'Braniewsko - Pasłęcki Bank Spółdzielczy z siedzibą w Pasłęku',
  '832': 'Bank Spółdzielczy w Sierakowicach',
  '833': 'Bank Spółdzielczy w Starogardzie Gdańskim',
  '834': 'Bank Spółdzielczy w Skórczu',
  '835': 'Gospodarczy Bank Spółdzielczy w Barlinku',
  '837': 'Bank Spółdzielczy w Rzepinie',
  '838': 'Bank Spółdzielczy Lwówek Śląski w Lwówku Śląskim',
  '840': 'Bank Spółdzielczy w Pleszewie',
  '841': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '843': 'Bank Spółdzielczy w Będzinie',
  '844': 'Bank Spółdzielczy w Pszczynie',
  '845': 'Bank Spółdzielczy Czechowice-Dziedzice-Bestwina',
  '846': 'Mikołowski Bank Spółdzielczy w Mikołowie',
  '849': 'Bank Spółdzielczy w Łopusznie',
  '851': 'Bank Spółdzielczy w Kielcach',
  '853': 'Bank Spółdzielczy w Witkowie',
  '854': 'Bank Spółdzielczy w Kłodawie',
  '855': 'Bank Spółdzielczy w Witkowie',
  '856': 'Ludowy Bank Spółdzielczy w Strzałkowie',
  '857': 'Bank Spółdzielczy w Sławnie',
  '858': 'Bank Spółdzielczy w Kaliszu Pomorskim',
  '859': 'Krakowski Bank Spółdzielczy',
  '862': 'Bank Spółdzielczy w Lipinkach',
  '865': 'Bank Spółdzielczy we Wschowie',
  '866': 'Bank Spółdzielczy we Wschowie',
  '868': 'Rejonowy Bank Spółdzielczy w Bychawie',
  '869': 'Rejonowy Bank Spółdzielczy w Bychawie',
  '870': 'Bank Spółdzielczy w Niemcach',
  '871': 'Bank Spółdzielczy w Lubartowie',
  '872': 'Bank Spółdzielczy w Radzyniu Podlaskim',
  '873': 'Powiatowy Bank Spółdzielczy w Opolu Lubelskim',
  '874': 'Powiatowy Bank Spółdzielczy w Opolu Lubelskim',
  '875': 'Bank Spółdzielczy w Kolnie',
  '877': 'Bank Spółdzielczy w Mońkach',
  '878': 'Bank Spółdzielczy Ziemi Kaliskiej',
  '879': 'Bank Spółdzielczy w Limanowej',
  '880': 'Łącki Bank Spółdzielczy',
  '882': 'Bank Spółdzielczy w Bartoszycach',
  '883': 'Bank Spółdzielczy w Nidzicy',
  '884': 'Bank Spółdzielczy w Szczytnie',
  '885': 'Bank Spółdzielczy w Bartoszycach',
  '886': 'Bank Spółdzielczy w Namysłowie',
  '887': 'Bank Spółdzielczy w Zawadzkiem',
  '888': 'Bank Spółdzielczy w Gogolinie',
  '890': 'Bank Spółdzielczy w Zawadzkiem',
  '891': 'Kurpiowski Bank Spółdzielczy w Myszyńcu',
  '892': 'Bank Spółdzielczy w Krasnosielcu z siedzibą w Makowie Mazowieckim',
  '893': 'Bank Spółdzielczy w Pułtusku',
  '894': 'Spółdzielczy Bank Ludowy w Złotowie',
  '895': 'Lubusko-Wielkopolski Bank Spółdzielczy',
  '896': 'naturoBank Bank Spółdzielczy',
  '898': 'Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim',
  '899': 'Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim',
  '900': 'Bank Spółdzielczy "MAZOWSZE" w Płocku',
  '901': 'Bank Spółdzielczy "MAZOWSZE" w Płocku',
  '903': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '904': 'Bank Spółdzielczy "Wspólna Praca" w Kutnie',
  '905': 'Powiatowy Bank Spółdzielczy we Wrześni',
  '906': 'Bank Spółdzielczy w Gnieźnie',
  '907': 'Bank Spółdzielczy Pojezierza Międzychodzko - Sierakowskiego w Sierakowie',
  '908': 'Bank Spółdzielczy Duszniki',
  '911': 'Bank Spółdzielczy Rzemiosła w Radomiu',
  '912': 'Bank Spółdzielczy w Zwoleniu',
  '913': 'Bank Spółdzielczy w Przysusze',
  '914': 'Bank Spółdzielczy Rzemiosła w Radomiu',
  '915': 'Bank Spółdzielczy Rzemiosła w Radomiu',
  '916': 'Bank Spółdzielczy w Strzyżowie',
  '917': 'Bank Spółdzielczy w Sędziszowie Młp.',
  '918': 'Bank Spółdzielczy w Przecławiu',
  '919': 'Bank Spółdzielczy w Siedlcach',
  '920': 'Bank Spółdzielczy w Krzywdzie',
  '921': 'Bank Spółdzielczy w Rykach',
  '922': 'Bank Spółdzielczy w Mińsku Mazowieckim',
  '923': 'Powiatowy Bank Spółdzielczy w Sokołowie Podlaskim',
  '924': 'Bank Spółdzielczy w Warcie',
  '925': 'Nadwarciański Bank Spółdzielczy w Działoszynie',
  '926': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '928': 'Rejonowy Bank Spółdzielczy w Lututowie',
  '929': 'Bank Spółdzielczy w Skierniewicach',
  '931': 'Bank Spółdzielczy w Ustce',
  '932': 'Bank Spółdzielczy w Bytowie',
  '933': 'Bank Spółdzielczy w Ustce',
  '934': 'Mazurski Bank Spółdzielczy w Giżycku',
  '935': 'Bank Spółdzielczy w Sejnach',
  '936': 'Bank Spółdzielczy w Sejnach',
  '937': 'Bank Spółdzielczy Ziemi Szczecińskiej',
  '938': 'Bank Spółdzielczy w Chojnie',
  '939': 'Bank Spółdzielczy w Tarnobrzegu',
  '940': 'Nadsański Bank Spółdzielczy',
  '941': 'Nadwiślański Bank Spółdzielczy w Solcu-Zdroju',
  '942': 'Bank Spółdzielczy w Sandomierzu',
  '943': 'Bank Spółdzielczy w Tarnobrzegu',
  '944': 'Bank Spółdzielczy Rzemiosła w Krakowie',
  '946': 'Bank Spółdzielczy Rzemiosła w Krakowie',
  '947': 'Bank Spółdzielczy w Pilźnie',
  '948': 'Bank Spółdzielczy w Brodnicy',
  '949': 'Bank Spółdzielczy w Brodnicy',
  '950': 'Bank Spółdzielczy w Łasinie',
  '951': 'Bank Spółdzielczy w Ząbkowicach Śląskich',
  '952': 'Bank Spółdzielczy w Ząbkowicach Śląskich',
  '953': 'Bank Spółdzielczy w Jaworze',
  '954': 'Kujawsko-Dobrzyński Bank Spółdzielczy',
  '957': 'Bank Spółdzielczy w Oławie',
  '959': 'Bank Spółdzielczy w Żmigrodzie',
  '960': 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  '961': 'Bank Spółdzielczy w Izbicy',
  '962': 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  '963': 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  '964': 'Powiatowy Bank Spółdzielczy w Zamościu',
  '965': 'Bank Spółdzielczy w Środzie Śląskiej',
  '966': 'Bank Spółdzielczy w Siedlcu',
  '967': 'Bank Spółdzielczy w Żaganiu',
};

export const BankName = {
  NBP: 'Narodowy Bank Polski',
  PKOBP: 'Powszechna Kasa Oszczędności Bank Polski Spółka Akcyjna',
  BankHandlowy: 'Bank Handlowy w Warszawie Spółka Akcyjna',
  Millenium: 'Bank Millennium Spółka Akcyjna',
  ING: 'ING Bank Śląski Spółka Akcyjna',
  BPH: 'Bank BPH Spółka Akcyjna',
  Santander: 'Santander Bank Polska Spółka Akcyjna',
  BGK: 'Bank Gospodarstwa Krajowego',
  mBank: 'mBank Spółka Akcyjna',
  BankHandlowoKredytowyWKatowicach: 'Bank Handlowo-Kredytowy Spółka Akcyjna w Katowicach w likwidacji',
  PekaoSA: 'Bank Polska Kasa Opieki Spółka Akcyjna',
  HSBC: 'HSBC Continental Europe (Spółka Akcyjna) Oddział w Polsce',
  BankPocztowy: 'Bank Pocztowy Spółka Akcyjna',
  DNB: 'DNB Bank Polska Spółka Akcyjna',
  VeloBank: 'VeloBank Spółka Akcyjna',
  BankOchronySrodowiska: 'Bank Ochrony Środowiska Spółka Akcyjna',
  BNPParibas: 'BNP Paribas Bank Polska Spółka Akcyjna',
  SGB: 'SGB-Bank Spółka Akcyjna',
  PlusBank: 'PLUS BANK Spółka Akcyjna',
  CreditAgricole: 'Credit Agricole Bank Polska Spółka Akcyjna',
  DanskeBank: 'Danske Bank A/S Spółka Akcyjna Oddział w Polsce',
  SocieteGenerale: 'Société Générale Spółka Akcyjna Oddział w Polsce',
  BNPParibasOddzialWPolsce: 'BNP Paribas S.A. Oddział w Polsce',
  NestBank: 'Nest Bank Spółka Akcyjna',
  DeutscheBank: 'Deutsche Bank Polska Spółka Akcyjna',
  PekaoHipoteczny: 'Pekao Bank Hipoteczny Spółka Akcyjna',
  BankPolskiejSpoldzielczości: 'BANK POLSKIEJ SPÓŁDZIELCZOŚCI SPÓŁKA AKCYJNA',
  SantanderConsumer: 'Santander Consumer Bank Spółka Akcyjna',
  VolksvagenBank: 'Volkswagen Bank GmbH Spółka z ograniczoną odpowiedzialnością Oddział w Polsce',
  CAAutoBank: 'CA Auto Bank S.p.A. Spółka Akcyjna Oddział w Polsce',
  mBankHipoteczny: 'mBank Hipoteczny Spółka Akcyjna',
  ToyotaBank: 'Toyota Bank Polska Spółka Akcyjna',
  SvenskaHandelsbanken: 'Svenska Handelsbanken AB Spółka Akcyjna Oddział w Polsce',
  RCIBanque: 'RCI Banque Spółka Akcyjna Oddział w Polsce',
  Raiffeisen: 'Raiffeisen Bank International AG (Spółka Akcyjna) Oddział w Polsce',
  SkandinaviskaEnskilda: 'Skandinaviska Enskilda Banken AB (Spółka Akcyjna) - Oddział w Polsce',
  CaixaBank: 'CAIXABANK, S.A. (SPÓŁKA AKCYJNA) ODDZIAŁ W POLSCE',
  USBank:
    'U.S. Bank Europe Designated Activity Company (Spółka z o.o. o Wyznaczonym Przedmiocie Działalności) Oddział w Polsce',
  HaitongBank: 'HAITONG BANK, S.A. Spółka Akcyjna Oddział w Polsce',
  AliorBank: 'Alior Bank Spółka Akcyjna',
  AarealBank: 'Aareal Bank Aktiengesellschaft (Spółka Akcyjna) - Oddział w Polsce',
  Citibank: 'Citibank Europe plc (Publiczna Spółka Akcyjna) Oddział w Polsce',
  IkanoBank: 'Ikano Bank AB (publ) Spółka Akcyjna Oddział w Polsce',
  NordeaBank: 'Nordea Bank Abp Spółka Akcyjna Oddział w Polsce',
  JPMorgan: 'J.P. Morgan SE (Spółka Europejska) Oddział w Polsce',
  BankOfChina: 'Bank of China (Europe) S.A. Spółka Akcyjna Oddział w Polsce',
  IndustrialCommercialBankOfChina:
    'Industrial and Commercial Bank of China (Europe) S.A. (Spółka Akcyjna) Oddział w Polsce',
  EuroclearBank: 'EUROCLEAR Bank SA/NV (Spółka Akcyjna) - Oddział w Polsce',
  IntesaSanpaolo: 'Intesa Sanpaolo S.p.A. Spółka Akcyjna Oddział w Polsce',
  WesternUnion: 'Western Union International Bank GmbH, Sp. z o.o. Oddział w Polsce',
  PKOHipoteczny: 'PKO Bank Hipoteczny Spółka Akcyjna',
  TFBank: 'TF BANK AB (Spółka Akcyjna) Oddział w Polsce',
  ASInbank: 'AS Inbank Spółka Akcyjna - Oddział w Polsce',
  ChinaConstructionBank: 'China Construction Bank (Europe) S.A. (Spółka Akcyjna) Oddział w Polsce',
  JohnDeereBank: 'John Deere Bank S.A. Spółka Akcyjna Oddział w Polsce',
  INGHipoteczny: 'ING Bank Hipoteczny Spółka Akcyjna',
  GoldmanSachsBank: 'Goldman Sachs Bank Europe SE Spółka Europejska Oddział w Polsce',
  BFFBank: 'BFF Bank S.p.A. Spółka Akcyjna Oddział w Polsce',
  BankNowy: 'Bank Nowy Spółka Akcyjna',
  Allfunds: 'Allfunds Bank S.A.U. (Spółka Akcyjna) Oddział w Polsce',
  HoistFinance: 'Hoist Finance AB (publ) Spółka Akcyjna Oddział w Polsce',
  MilleniumHipoteczny: 'Millennium Bank Hipoteczny Spółka Akcyjna',
  AIONBank: 'AION Bank S.A. Spółka Akcyjna Oddział w Polsce',
  MorganStanleyBank: 'Morgan Stanley Europe SE (Spółka Europejska) Oddział w Polsce',
  WooriBank: 'Woori Bank Europe GmbH spółka z ograniczoną odpowiedzialnością Oddział w Polsce',
  BSOtwock: 'Bank Spółdzielczy w Otwocku',
  BSHalinowo: 'Bank Spółdzielczy w Halinowie',
  BSKarczewo: 'Bank Spółdzielczy w Karczewie',
  BSTrzebieszewo: 'Bank Spółdzielczy w Trzebieszowie',
  BSLomazy: 'Bank Spółdzielczy w Łomazach',
  BSBialaPodlaska: 'Bank Spółdzielczy w Białej Podlaskiej',
  BSBialystok: 'Bank Spółdzielczy w Białymstoku',
  BSHajnówka: 'Bank Spółdzielczy w Hajnówce',
  BSSokolka: 'Bank Spółdzielczy w Sokółce',
  BSKalwariaZebrzydowska: 'Bank Spółdzielczy w Kalwarii Zebrzydowskiej',
  ABS: 'ABS Bank Spółdzielczy',
  BSPiotrkowKujawski: 'Bank Spółdzielczy w Piotrkowie Kujawskim',
  BSNakloNadNotecia: 'Bank Spółdzielczy w Nakle n/Notecią',
  BSChelm: 'Wschodni Bank Spółdzielczy w Chełmie',
  BSLesniowice: 'Bank Spółdzielczy w Leśniowicach',
  BSPultusk: 'Bank Spółdzielczy w Pułtusku',
  BSGlinojeck: 'Bank Spółdzielczy w Glinojecku',
  BSPlonsk: 'Bank Spółdzielczy w Płońsku',
  BSKrzepice: 'Bank Spółdzielczy w Krzepicach',
  BSCzestochowa: 'Częstochowski Bank Spółdzielczy JURA BANK',
  BSKonopiska: 'Bank Spółdzielczy w Konopiskach',
  BSMyszkow: 'Międzypowiatowy Bank Spółdzielczy w Myszkowie',
  BSMalbork: 'Bank Spółdzielczy w Malborku',
  BSPaslek: 'Braniewsko - Pasłęcki Bank Spółdzielczy z siedzibą w Pasłęku',
  BSSierakowice: 'Bank Spółdzielczy w Sierakowicach',
  BSStarogardGdanski: 'Bank Spółdzielczy w Starogardzie Gdańskim',
  BSSkorcz: 'Bank Spółdzielczy w Skórczu',
  BSBarlinek: 'Gospodarczy Bank Spółdzielczy w Barlinku',
  BSRzepin: 'Bank Spółdzielczy w Rzepinie',
  BSLwowekSlaski: 'Bank Spółdzielczy Lwówek Śląski w Lwówku Śląskim',
  BSPleszewo: 'Bank Spółdzielczy w Pleszewie',
  BSLututow: 'Rejonowy Bank Spółdzielczy w Lututowie',
  BSBedzin: 'Bank Spółdzielczy w Będzinie',
  BSPszczyna: 'Bank Spółdzielczy w Pszczynie',
  BSCzechowiceDziedziceBestwina: 'Bank Spółdzielczy Czechowice-Dziedzice-Bestwina',
  BSMikolow: 'Mikołowski Bank Spółdzielczy w Mikołowie',
  BSLopuszno: 'Bank Spółdzielczy w Łopusznie',
  BSKielce: 'Bank Spółdzielczy w Kielcach',
  BSWitkow: 'Bank Spółdzielczy w Witkowie',
  BSKlodawa: 'Bank Spółdzielczy w Kłodawie',
  BSStrzalkow: 'Ludowy Bank Spółdzielczy w Strzałkowie',
  BSSlawno: 'Bank Spółdzielczy w Sławnie',
  BSKaliszPomorski: 'Bank Spółdzielczy w Kaliszu Pomorskim',
  BSKrakow: 'Krakowski Bank Spółdzielczy',
  BSLipinki: 'Bank Spółdzielczy w Lipinkach',
  BSWschowo: 'Bank Spółdzielczy we Wschowie',
  BSBychawa: 'Rejonowy Bank Spółdzielczy w Bychawie',
  BSNiemcy: 'Bank Spółdzielczy w Niemcach',
  BSLubartow: 'Bank Spółdzielczy w Lubartowie',
  BSRadzyniuPodlaskim: 'Bank Spółdzielczy w Radzyniu Podlaskim',
  BSOpoleLubelskie: 'Powiatowy Bank Spółdzielczy w Opolu Lubelskim',
  BSKolno: 'Bank Spółdzielczy w Kolnie',
  BSMonki: 'Bank Spółdzielczy w Mońkach',
  BSZiemiaKaliska: 'Bank Spółdzielczy Ziemi Kaliskiej',
  BSLimanowa: 'Bank Spółdzielczy w Limanowej',
  BSLacko: 'Łącki Bank Spółdzielczy',
  BSBartoszyce: 'Bank Spółdzielczy w Bartoszycach',
  BSNidzica: 'Bank Spółdzielczy w Nidzicy',
  BSSzczytno: 'Bank Spółdzielczy w Szczytnie',
  BSNamyslow: 'Bank Spółdzielczy w Namysłowie',
  BSZawadzkie: 'Bank Spółdzielczy w Zawadzkiem',
  BSGogolin: 'Bank Spółdzielczy w Gogolinie',
  BSMyszyniec: 'Kurpiowski Bank Spółdzielczy w Myszyńcu',
  BSMakowMazowiecki: 'Bank Spółdzielczy w Krasnosielcu z siedzibą w Makowie Mazowieckim',
  BSZlotow: 'Spółdzielczy Bank Ludowy w Złotowie',
  BSLubuskoWielkopolski: 'Lubusko-Wielkopolski Bank Spółdzielczy',
  BSNaturoBank: 'naturoBank Bank Spółdzielczy',
  BSTomaszowMazowiecki: 'Powiatowy Bank Spółdzielczy w Tomaszowie Mazowieckim',
  BSMazowsze: 'Bank Spółdzielczy "MAZOWSZE" w Płocku',
  BSWspolnaPraca: 'Bank Spółdzielczy "Wspólna Praca" w Kutnie',
  BSWrzesnia: 'Powiatowy Bank Spółdzielczy we Wrześni',
  BSGniezno: 'Bank Spółdzielczy w Gnieźnie',
  BSSierakow: 'Bank Spółdzielczy Pojezierza Międzychodzko - Sierakowskiego w Sierakowie',
  BSDuszniki: 'Bank Spółdzielczy Duszniki',
  BSRadom: 'Bank Spółdzielczy Rzemiosła w Radomiu',
  BSZwolen: 'Bank Spółdzielczy w Zwoleniu',
  BSPrzysusza: 'Bank Spółdzielczy w Przysusze',
  BSStrzyzow: 'Bank Spółdzielczy w Strzyżowie',
  BSSedziszowMalopolski: 'Bank Spółdzielczy w Sędziszowie Młp.',
  BSPrzeclaw: 'Bank Spółdzielczy w Przecławiu',
  BSSiedlce: 'Bank Spółdzielczy w Siedlcach',
  BSKrzywdzie: 'Bank Spółdzielczy w Krzywdzie',
  BSRykach: 'Bank Spółdzielczy w Rykach',
  BSMinskMazowiecki: 'Bank Spółdzielczy w Mińsku Mazowieckim',
  BSSokolowPodlaski: 'Powiatowy Bank Spółdzielczy w Sokołowie Podlaskim',
  BSWarta: 'Bank Spółdzielczy w Warcie',
  BSDzieloszyn: 'Nadwarciański Bank Spółdzielczy w Działoszynie',
  BSSkierniewice: 'Bank Spółdzielczy w Skierniewicach',
  BSUstka: 'Bank Spółdzielczy w Ustce',
  BSBytow: 'Bank Spółdzielczy w Bytowie',
  BSGizycko: 'Mazurski Bank Spółdzielczy w Giżycku',
  BSSejny: 'Bank Spółdzielczy w Sejnach',
  BSZiemiaSzczecinska: 'Bank Spółdzielczy Ziemi Szczecińskiej',
  BSChojno: 'Bank Spółdzielczy w Chojnie',
  BSTarnobrzeg: 'Bank Spółdzielczy w Tarnobrzegu',
  BSNadsanski: 'Nadsański Bank Spółdzielczy',
  BSSolecZdroj: 'Nadwiślański Bank Spółdzielczy w Solcu-Zdroju',
  BSSandomierz: 'Bank Spółdzielczy w Sandomierzu',
  BSRzemioslaKrakow: 'Bank Spółdzielczy Rzemiosła w Krakowie',
  BSPilzno: 'Bank Spółdzielczy w Pilźnie',
  BSBrodnica: 'Bank Spółdzielczy w Brodnicy',
  BSLasin: 'Bank Spółdzielczy w Łasinie',
  BSZabkowiceSlaskie: 'Bank Spółdzielczy w Ząbkowicach Śląskich',
  BSJawor: 'Bank Spółdzielczy w Jaworze',
  BSKujawskoDobrzynski: 'Kujawsko-Dobrzyński Bank Spółdzielczy',
  BSOlawa: 'Bank Spółdzielczy w Oławie',
  BSZmigrodzie: 'Bank Spółdzielczy w Żmigrodzie',
  BSTomaszowLubelski: 'Bank Spółdzielczy w Tomaszowie Lubelskim',
  BSIzbica: 'Bank Spółdzielczy w Izbicy',
  BSZamosc: 'Powiatowy Bank Spółdzielczy w Zamościu',
  BSSrodaSlaska: 'Bank Spółdzielczy w Środzie Śląskiej',
  BSSiedlec: 'Bank Spółdzielczy w Siedlcu',
  BSZagan: 'Bank Spółdzielczy w Żaganiu',
} as const;
export type BankName = (typeof BankName)[keyof typeof BankName];

const IBAN_REGEX = /^([A-Z]{2})?(\d{2})(\d{3})(\d{8,25})$/i;
const IBAN_BANK_DATA_REGEX = /^(?:[A-Z]{2})?\d{2}(\d{3})/i;

function _modulo(number: string, mod: number): number {
  let result = 0;
  for (let i = 0; i < number.length; i++) {
    result = parseInt(result.toString() + number[i]) % mod;
  }
  return result;
}

/**
 * Validates an International Bank Account Number (IBAN). The function checks for
 * proper length, format, and passes the IBAN checksum requirements. In the case of
 * IBANs starting with `PL` (or with no country code), the 3rd-5th digits are validated
 * against a list of Polish banks. Any whitespace is ignored, but other characters will
 * result in the IBAN being invalid.
 *
 * @param {string} iban - The IBAN number as a string, with or without spaces.
 * @returns {boolean} `true` if the IBAN is valid; `false` otherwise.
 */
export function isIbanValid(iban: string): boolean {
  iban = removeWhitespace(iban).toUpperCase();

  // Validate the structure using the regex.
  const match = iban.match(IBAN_REGEX);
  if (!match) {
    return false;
  }
  // Destructure the regex match, defaulting to 'PL' if the country code is missing.
  const [, countryCode = 'PL', controlSum, bankNameNumber, rest] = match;

  // Check the overall length for the given country.
  if (
    !IBAN_COUNTRY_DATA[countryCode] ||
    controlSum.length + bankNameNumber.length + rest.length + 2 !== IBAN_COUNTRY_DATA[countryCode].length
  ) {
    return false;
  }

  // For Polish IBANs, verify that the bank code is in our known list.
  if (countryCode === 'PL' && !BANK_NAMES[bankNameNumber]) {
    return false;
  }

  // Rearrange the IBAN: move the first 4 characters (country code and control sum)
  // to the end. The BBAN (bankNameNumber + rest) comes first.
  const rearranged =
    bankNameNumber +
    rest +
    (countryCode.charCodeAt(0) - 55).toString() +
    (countryCode.charCodeAt(1) - 55).toString() +
    controlSum;
  const checkSum = _modulo(rearranged, 97);

  return checkSum === 1;
}

/**
 * Returns true if the IBAN is invalid; false otherwise.
 *
 * @param {string} iban - The IBAN number as a string.
 * @returns {boolean}
 */
export const isIbanInvalid = (iban: string) => !isIbanValid(iban);

/**
 * Extracts country-specific information from the IBAN.
 *
 * @param {string} iban - The IBAN number as a string.
 * @returns {{ country: string; length: number } | null} An object containing the country name
 * and IBAN length for the given IBAN, or `null` if not valid.
 */
export function getCountryIbanDataFromIban(iban: string): { country: string; length: number } | null {
  iban = removeWhitespace(iban).toUpperCase();
  if (iban.length < 2) {
    return null;
  }
  const countryCode = iban.slice(0, 2);
  return IBAN_COUNTRY_DATA[countryCode] ?? null;
}

/**
 * Fetches the bank name based on the IBAN, specifically for Polish IBANs.
 * If a non-Polish IBAN is supplied, it will always return `null`.
 *
 * @param {string} iban - The IBAN number as a string.
 * @returns {string | null} The bank name as a string, or `null` if not available.
 */
export function getBankNameFromIban(iban: string): string | null {
  iban = removeWhitespace(iban).toUpperCase();
  if (!iban.startsWith('PL')) {
    return null;
  }
  const match = iban.match(IBAN_BANK_DATA_REGEX);
  if (!match) {
    return null;
  }
  const bankCode = match[1];
  return BANK_NAMES[bankCode] ?? null;
}

/**
 * Fetches the full bank name based on the IBAN, specifically for Polish IBANs.
 * If a non-Polish IBAN is supplied, it will always return `null`.
 *
 * @param {string} iban - The IBAN number as a string.
 * @returns {string | null} The full bank name as a string, or `null` if not available.
 */
export function getFullBankNameFromIban(iban: string): string | null {
  iban = removeWhitespace(iban).toUpperCase();
  if (!iban.startsWith('PL')) {
    return null;
  }
  const match = iban.match(IBAN_BANK_DATA_REGEX);
  if (!match) {
    return null;
  }
  const bankCode = match[1];
  return BANK_FULL_NAMES[bankCode] ?? null;
}
